version: '3'
services:
  crust-rocky:
    image: crustio/crust:rocky
    network_mode: host
    restart: always
    command:
      - "./crust"
      - --base-path
      - /tmp/rocky-watcher
      - --chain
      - rocky
      - --name
      - rocky-watcher
      - --port
      - "30333"
      - --ws-port
      - "9944"
      - --rpc-port
      - "9933"
      - --rpc-external
      - --ws-external
      - --rpc-cors
      - all
      - --ws-max-connections
      - "1000"
      - --in-peers
      - "100"
      - --no-telemetry
      - --execution
      - "WASM"
    volumes:
      - /tmp/rocky-watcher:/tmp/rocky-watcher
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"